FROM harbor-pks-dev01.server.rbsgrp.net/iamp/pingaccess:5.3.2-edge
#FROM pingidentity/pingaccess:5.3.2-edge
#FROM pingidentity/pingaccess:2005
COPY pingaccess/. /opt/in/.

#
#source ~/.profile 
#eval $(minikube docker-env)
#docker images
#docker build --tag pingidentity/pingaccess:5.3.2-edge-rbs .
#docker push pingidentity/pingaccess:5.3.2-edge-rbs
#docker push $(minikube ip):5000/pingidentity/pingaccess:5.3.2-edge-rbs
