apiVersion: v1
kind: Service
metadata:
  name: pingaccess-engine
  labels:
    role: pingaccess
    tier: engine
spec:
  ports:
    - port: 8443
      targetPort: 3000
      name: https
  selector:
    role: pingaccess
    tier: engine
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingaccess
  labels:
    role: pingaccess
    tier: engine
spec:
  replicas: 1
  selector:
    matchLabels:
      role: pingaccess
      tier: engine
  template:
    metadata:
      name: pingaccess
      labels:
        role: pingaccess
        tier: engine
    spec:
      initContainers:
      - name: init
        image: harbor-pks-dev01.server.rbsgrp.net/iamp/curl:latest
        command: ['sh', '-c', 'until curl --connect-timeout 1 --silent -k https://pingaccess:8443 ; do echo waiting for admin ; sleep 3 ; done']
      containers:
      - name: pingaccess
        image: harbor-pks-dev01.server.rbsgrp.net/iamp/pingaccess:5.3.2-edge-rbs
        imagePullPolicy: Always
        #image: pingidentity/pingaccess:6.1.0-edge
        #image: pingidentity/pingaccess:edge
        ports:        
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: pingaccess-engine-environment-variables
        #- secretRef:
        #    name: devops-secret
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - /opt/liveness.sh
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - /opt/liveness.sh
          initialDelaySeconds: 100
          periodSeconds: 30
